# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Aetherea"
title_separator: "-"
subtitle: "A magical world."
email: "czerkas.tim@student.dhbw-karlsruhe.de"
description: "Aetherea is a magical world, where you can create your own spells and fight against other wizards. You can find the Repository on GitHub."
minimal_mistakes_skin: dark
search: true
repository: "Aetherea/aetherea.github.io"
comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "pathname"

# Build settings
markdown: GFM
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Berlin" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Aetherea Devs"
  avatar: "/images/wizard1.jpg"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Aetherea"
    - label: "Game Repository"
      icon: "fas fa-fw fa-gamepad"
      url: "https://github.com/Aetherea/Aetherea-Game"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      
      classes: wide
      author_profile: true
      read_time: true
      words_per_minute: 80
      comments: true
      share: false
      related: false
  # _pages    
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false
      comments: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
